id: /subscriptions/977171a9-6bfd-49c4-a496-018d3312466e/resourceGroups/azure-container-apps/providers/Microsoft.App/containerapps/nginx
identity:
  type: None
location: West Europe
name: nginx
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: nginx.gentlepebble-7a25fea7.westeurope.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 80
      targetPortHttpScheme: null
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: null
    registries: null
    secrets: null
    service: null
  customDomainVerificationId: BF4B33B152939A4939D9AC49F4B9EE99AA8A15E470FC2DEBD4B199F5215D8EFC
  environmentId: /subscriptions/977171a9-6bfd-49c4-a496-018d3312466e/resourceGroups/azure-container-apps/providers/Microsoft.App/managedEnvironments/env-container-apps-environment
  eventStreamEndpoint: https://westeurope.azurecontainerapps.dev/subscriptions/977171a9-6bfd-49c4-a496-018d3312466e/resourceGroups/azure-container-apps/containerApps/nginx/eventstream
  latestReadyRevisionName: nginx--99a53v9
  latestRevisionFqdn: nginx--99a53v9.gentlepebble-7a25fea7.westeurope.azurecontainerapps.io
  latestRevisionName: nginx--99a53v9
  managedEnvironmentId: /subscriptions/977171a9-6bfd-49c4-a496-018d3312466e/resourceGroups/azure-container-apps/providers/Microsoft.App/managedEnvironments/env-container-apps-environment
  outboundIpAddresses:
  - 20.73.234.124
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - image: nginx
      name: nginx
      volumeMounts:
      - volumeName: mounted-azure-file-volume
        mountPath: /var/log/nginx
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      maxReplicas: 1
      minReplicas: 1
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes:
    - name: mounted-azure-file-volume
      storageName: acamountedshare
      storageType: AzureFile
  workloadProfileName: null
resourceGroup: azure-container-apps
systemData:
  createdAt: '2024-02-20T12:25:34.6133672'
  createdBy: admin@eladtal.com
  createdByType: User
  lastModifiedAt: '2024-02-20T12:25:34.6133672'
  lastModifiedBy: admin@eladtal.com
  lastModifiedByType: User
type: Microsoft.App/containerApps
