on: [push]
name: Build&Push opentofu .NET-Queue Container App Job image to ACR

jobs:
  buildImage:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: copy shared files
          run: cp -r ./shared/{installer.sh,runner.sh} ./dotnet-queue/OpenTofu/
        - name: list app files
          run: ls -la ./dotnet-queue/OpenTofu/
        - name: Build and push opentofu-dotnet-queue image to ACR (${{ vars.CONTAINER_REGISTRY }})
          run: az acr build --image opentofu-dotnet-queue:latest --registry ${{ vars.CONTAINER_REGISTRY }} --resource-group ${{ vars.RESOURCE_GROUP }} --file ./dotnet-queue/OpenTofu/Dockerfile ./dotnet-queue/OpenTofu/
        - name: retag image with sha
          run: az acr import --name ${{ vars.CONTAINER_REGISTRY }} --source ${{ vars.CONTAINER_REGISTRY }}.azurecr.io/opentofu-dotnet-queue:latest --image opentofu-dotnet-queue:${{ github.sha }} --force
        - name: Build and deploy Container App
          run: |
            az containerapp job update \
              --resource-group ${{ vars.RESOURCE_GROUP }} \
              --name opentofu-dotnet-queue \
              --image ${{ vars.CONTAINER_REGISTRY }}.azurecr.io/opentofu-dotnet-queue:latest

          ## works only on continaer apps, not container jobs
          # uses: azure/container-apps-deploy-action@v1
          # with:
          #   acrName: ${{ vars.CONTAINER_REGISTRY }}
          #   containerAppName: opentofu-dotnet-queue
          #   resourceGroup: ${{ vars.RESOURCE_GROUP }}
          #   imageToDeploy: ${{ vars.CONTAINER_REGISTRY }}.azurecr.io/opentofu-dotnet-queue:latest        
