on: [push]
name: Build&Push opentofu .NET-Queue Container App Job image to ACR

jobs:
  buildImage:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: copy shared files
          run: cp -r ./shared/* ./dotnet-queue/OpenTofu/
        - name: list app files
          run: ls -la ./dotnet-queue/OpenTofu/
        - name: Build and push opentofu-dotnet-queue image to ACR (${{ vars.CONTAINER_REGISTRY }})
          run: az acr build --image opentofu-dotnet-queue:latest --registry ${{ vars.CONTAINER_REGISTRY }} --resource-group ${{ vars.RESOURCE_GROUP }} --file ./dotnet-queue/OpenTofu/Dockerfile ./dotnet-queue/OpenTofu/
