on: [push]
name: Build&Push opentofu Container App image to Azure Container Registry (ACR)

jobs:
  buildImage:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Build and push opentofu image to ACR (${{ vars.CONTAINER_REGISTRY }})
          run: az acr build --image opentofu:latest --registry ${{ vars.CONTAINER_REGISTRY }} -g ${{ vars.RESOURCE_GROUP }} -f ./app/Dockerfile ./app/
