on: [push]
name: Build&Push opentofu Python-Blob Container App Job image to ACR

jobs:
  buildImage:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: copy shared files
          run: cp -r ./shared/{installer.sh,runner.sh} ./python-blob/app/
        - name: list app files
          run: ls -la ./python-blob/app/
        - name: Build and push opentofu-python-blob image to ACR (${{ vars.CONTAINER_REGISTRY }})
          run: az acr build --image opentofu-python-blob:latest --registry ${{ vars.CONTAINER_REGISTRY }} --resource-group ${{ vars.RESOURCE_GROUP }} --file ./python-blob/Dockerfile ./python-blob/app/
